[project]
name = "g-calendar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "google-api-python-client>=2.177.0",
    "google-auth-httplib2>=0.2.0",
    "google-auth-oauthlib>=1.2.2",
    "loguru>=0.7.3",
    "mcp>=1.12.2",
    "openai>=1.97.1",
]

[tool.deptry.per_rule_ignores]
DEP001 = ["core"]
DEP002 = ["google-auth-httplib2"]
DEP003 = ["google","requests"]



[dependency-groups]
dev = [
    "deptry>=0.23.0",
    "interrogate>=1.7.0",
    "pre-commit>=4.2.0",
    "vulture>=2.14",
]
