[project]
name = "g-calendar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-api-python-client>=2.177.0",
    "google-auth-httplib2>=0.2.0",
    "google-auth-oauthlib>=1.2.2",
]

[dependency-groups]
dev = [
    "deptry>=0.23.0",
    "interrogate>=1.7.0",
    "loguru>=0.7.3",
    "pre-commit>=4.2.0",
    "vulture>=2.14",
]
